resilience4j.retry:
    configs:
        default:
            maxAttempts: 20
            waitDuration: 1000
            retryExceptions:
                - org.springframework.web.client.HttpServerErrorException
                - java.util.concurrent.TimeoutException
                - java.io.IOException
                - java.net.SocketException
        selenium:
            maxAttempts: 100
            waitDuration: 10000
            retryExceptions:
                - org.openqa.selenium.WebDriverException
                - org.openqa.grid.common.exception.GridException
        neo4j:
            maxAttempts: 10
            waitDuration: 1000
            retryExceptions:
                - org.neo4j.ogm.exception.ConnectionException
                - org.neo4j.driver.exceptions.SessionExpiredException
                - org.neo4j.driver.exceptions.DiscoveryException
    instances:
        neo4j:
            baseConfig: neo4j
        webdriver:
            baseConfig: selenium
        gcp:
            baseConfig: default