resilience4j.retry:
    configs:
        default:
            maxAttempts: 5
            waitDuration: 5000
            retryExceptions:
                - org.springframework.web.client.HttpServerErrorException
                - java.util.concurrent.TimeoutException
                - java.io.IOException
                - java.net.SocketException
                - java.net.ConnectException
                - java.lang.Exception
        webdriver:
            maxAttempts: 10000
            waitDuration: 100
            retryExceptions:
                - org.openqa.selenium.WebDriverException
                - org.openqa.grid.common.exception.GridException
                - org.openqa.selenium.remote.UnreachableBrowserException
                - org.openqa.selenium.NoSuchSessionException
                - java.io.IOException
                - java.net.ConnectException
                - java.lang.Exception
        neoforj:
            maxAttempts: 1000
            waitDuration: 500
            retryExceptions:
                - org.neo4j.ogm.exception.ConnectionException
                - org.neo4j.driver.exceptions.SessionExpiredException
                - org.neo4j.driver.exceptions.DiscoveryException
                - org.neo4j.driver.exceptions.TransientException
                - org.neo4j.ogm.exception.TransactionException
                - java.net.SocketException
                - java.lang.Exception
        gcp:
            maxAttempts: 10
            waitDuration: 500
            retryExceptions:
                - java.io.IOException
                - com.google.cloud.storage.StorageException
    instances:
        neoforj:
            baseConfig: neoforj
        webdriver:
            baseConfig: webdriver
        gcp:
            baseConfig: gcp
        default:
            baseConfig: default