resilience4j.retry:
    configs:
        default:
            maxAttempts: 20
            waitDuration: 1000
            retryExceptions:
                - org.springframework.web.client.HttpServerErrorException
                - java.util.concurrent.TimeoutException
                - java.io.IOException
                - java.net.SocketException
        selenium:
            maxAttempts: 200
            waitDuration: 2000
            retryExceptions:
                - org.openqa.selenium.WebDriverException
                - org.openqa.grid.common.exception.GridException
        neo4j:
            maxAttempts: 10
            waitDuration: 1000
            retryExceptions:
                - org.neo4j.ogm.exception.ConnectionException
                - org.neo4j.driver.exceptions.SessionExpiredException
                - org.neo4j.driver.exceptions.DiscoveryException
                - java.net.SocketException
        gcp:
            maxAttempts: 10
            waitDuration: 500
            retryExceptions:
                - java.io.IOException
                - com.google.cloud.storage.StorageException
    instances:
        neo4j:
            baseConfig: neo4j
        webdriver:
            baseConfig: selenium
        gcp:
            baseConfig: gcp