name: CI/CD Pipeline 🚀

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows manual trigger too!

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Extract version from pom.xml
        id: project_version
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ env.VERSION }}.jar
          path: target/*.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Only release from main branch

    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: app-${{ env.VERSION }}.jar

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          body: |
            🎉 New release of the app!
            Version: v${{ env.VERSION }}
          draft: false
          prerelease: false
          files: app-${{ env.VERSION }}.jar
